name: Backend_CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 3000:3000
        # options: >-
        #   --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongo --quiet"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run Vitest tests
        run: |
          cd backend
          npm run test
